language: scala

sudo: required
dist: trusty
services: docker

addons:
  apt:
    packages:
      - shellcheck

env:
  matrix:
    - RELEASE=false

before_install:
  - git fetch --tags
  - docker pull exasol/docker-db:latest

matrix:
  include:
    - jdk: openjdk8
      scala: 2.11.12

    - jdk: oraclejdk8
      scala: 2.11.12

    - jdk: openjdk8
      scala: 2.12.7

    - jdk: oraclejdk8
      scala: 2.12.7
      env: RELEASE=false

script:
  - travis_wait 30 ./scripts/ci.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - "$HOME/.sbt/1.0"
    - "$HOME/.sbt/boot/scala*"
    - "$HOME/.sbt/cache"
    - "$HOME/.sbt/launchers"
    - "$HOME/.ivy2"
    - "$HOME/.coursier"

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
